[build]
  publish = "dist/memory-verse/browser"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://memoryverse-backend-mkap.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
